name: CD - Deploy to Cloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Build Docker image and Push to AWS ECR and Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Kube Control
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.0'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backstract_apps
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:zepra-crm-apis-coll-0d29d6fc92584f668b0a7c738476ae52 .
          docker push -a $REGISTRY/$REPOSITORY

      - name: Update kube config to point to EKS
        run: aws eks update-kubeconfig --name backstract-dev --region ap-south-1

      - name: Deploy image to Amazon EKS
        run: |
          kubectl apply -f infra/k8s/aws-auth.yaml
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/service.yaml
          kubectl rollout restart deployment zepra-crm-apis-coll-0d29d6fc92584f668b0a7c738476ae52-depl